### ISSUE TITLE
Issue with yarn add

### ISSUE THREAD

**Issue by daraclare** [cmfcmf/docusaurus-search-local#1]
Hi, thanks for a really useful plugin, I'm trying to use it in a new Docusaurus v2 project, but I get this bug when running `yarn add @cmfcmf/docusaurus-search-local`

```
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://registry.yarnpkg.com/@babel/helper-wrap-function/-/helper-wrap-function-7.8.3.tgz: Integrity check failed for "@babel/helper-wrap-function" (computed integrity doesn't match our records, got "sha512-LACJrbUET9cQDzb6kG7EeD7+7doC3JNvUgTEQOx2qaO1fKlzE/Bf05qs9w1oXQMmXlPO65lC3Tq9S6gZpTErEQ== sha1-nb2yu1XvFKqgH+jJm2Kb1TUthhA=")
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

Also, my `docusaurus.config.js` file has no plugin property, so I added one, I'm hoping that won't cause an issue.

**Comment by cmfcmf** [comment]
Hi @daraclare,
I can't reproduce this issue :/ I tried the following and it worked:
```bash
npx @docusaurus/init@next init my-website classic
cd my-website
yarn add @cmfcmf/docusaurus-search-local
```
I'm not sure whether the problem is an issue with this plugin or rather an issue with Yarn. A google search suggests that running `yarn --update-checksums` might fix the problem: https://github.com/yarnpkg/yarn/issues/6407#issuecomment-536107853

**Comment by daraclare** [comment]
Apologies, it seems to be an issue with something locally 🙈 I've started my docusaurus-init again and it works, sorry, I should have looked into it more before creating an issue!
