### ISSUE TITLE
Customizable search button

### ISSUE THREAD

**Issue by LookRain** [cmfcmf/docusaurus-search-local#107]
I'm very satisfied with this plugin so far, however, the default search button does not really fit my docsite. So is there any way to customize the UI for the button? If not, is it a planned feature for future versions? thanks

![image](https://user-images.githubusercontent.com/11829847/159619328-a9e5c702-413c-41c7-aeab-3147cbdef1c7.png)

**Comment by marcusnewton** [comment]
You can target it using the global stylesheet under `src/css/custom.css`

**Comment by LookRain** [comment]
got it. It works for me for now, but it would be great if we can replace the default button with a React component if the design deviates from the default one too much and customizing CSS is not enough.

**Comment by gentledepp** [comment]
Could you please give me a hint what I am doing wrong?

1) I installed the plugin just as described in your wiki and a normal docusaurus v2 configuration using presets classic:
![image](https://user-images.githubusercontent.com/1175751/165525313-77d77362-e0e7-4389-9dd7-e70747fe1039.png)


2) when adding the following lines to my custom css, they do not have any effect:
![image](https://user-images.githubusercontent.com/1175751/165525462-e254b87c-d143-44fc-8ed9-718f213859b4.png)


So I fired up chrome dev tools and it seems, that my custom.css is inserted into the html BEFORE the searchbar css is added:
![image](https://user-images.githubusercontent.com/1175751/165525958-217e64fb-c45e-4598-8bed-c2ca35df7be9.png)

So 
1. is there a way to change the order of the css definitions, so that my custom.css can actually *override* the existing variables?
2. or am I doing something fundamentally wrong here?

**Comment by ItsJustMiaouss** [comment]
Hey @gentledepp,

If you want to change the color using the root variables you have to:
  1. Use the [RGB colors](https://g.co/kgs/9hbns1) instead of the default CSS shortcut or HEX (e.g `255, 0, 0` instead of `red` or `#ff1100`).
  2. Make sure you have set the priority `!important` after defining the color to override the previous styling rules.
 
Example:
```css
:root {
  --aa-primary-color-rgb: 255, 0, 0 !important;
  --aa-muted-color-rgb: 255, 0, 0 !important;
  /* ... */
}
```

If you use the dark theme, then replace `:root { ... }` by `[data-theme='dark'] { ... }`.

**Comment by gentledepp** [comment]
This totally worked. Thank you so much!!

**Comment by cmfcmf** [comment]
Thanks @ItsJustMiaouss! I linked your comment from the README :)

**Comment by stevehenderson** [comment]
I also had issues with the search bar compressing large text into a small box.

A workaround:  I changed the color of the text so that only the icon was displayed.  

In your docusaurus file `src/css/custom.css` add these at the bottom:

```
[data-theme='light'] .DocSearch-Button-Placeholder  {
  color:#f4f4f4 !important;  
}

[data-theme='dark'] .DocSearch-Button-Placeholder {
  color:#6b6b6b !important;  
}

[data-theme='light'] .DocSearch-Button-Keys  {
  color:#f4f4f4 !important;  
}

[data-theme='dark'] .DocSearch-Button-Keys {
  color:#6b6b6b !important;  
}
```
