### ISSUE TITLE
is search not supported for other language which is not mentioned on doc?

### ISSUE THREAD

**Issue by code-masala** [cmfcmf/docusaurus-search-local#74]
@cmfcmf  For other language search-index.json is generated perfectly fine.But in search bar only supported the locale language en .For other language no results.

**Comment by cmfcmf** [comment]
I am not 100% sure what the issue is here. It should currently work like so:
Let's say your documentation is in two languages, English and German. You have configured them in your `docusaurus.config.js` like this:
```js
 i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de'],
    localeConfigs: {
      en: {
        label: 'English',
      },
      de: {
        label: 'Deutsch',
      },
    },
  },
```

Then, the search bar will use the German search index when you are on a German docs page, and the English search index, when you are on an English docs page.
Please let me know if that doesn't work for you :)
